name: super_simple_storage
description: A very simple storage system for Flutter and Dart.
version: 1.0.0
homepage: https://github.com/TommasoAzz/super_simple_storage

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  path: ^1.8.0
  meta: ^1.7.0

dev_dependencies:
  test: ^1.20.1
  json_serializable: ^6.1.4
  build_runner: ^2.1.7